name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: | 
        dotnet test Fractions/UnitTest.sln --logger "junit;LogFilePath=dotnet-test-result.xml" --collect:"XPlat Code Coverage"

        # find and print the output file
        OUTPUT=$(find tests/TestResults | grep xml)
        echo "${OUTPUT}"

        # produce the report
        /root/.dotnet/tools/reportgenerator -reports:${OUTPUT} -reporttypes:Html -targetdir:html
        /root/.dotnet/tools/reportgenerator -reports:${OUTPUT} -reporttypes:TextSummary -targetdir:text
